name: Projeto-cypress-Page-Ojects
on:
  push:
    branches: [main] # ---> escolher a banch que serÃ¡ executada
  
jobs:
  Teste-Page-Objects: #Nome do teste (ou projeto)
    runs-on: ubuntu-22.04
   
    steps:
      - name: Checkout # ---> baixar o projeto e instalar as dependencias (pesquisar na lateral por: Cypress.io)
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3 # ---> startar node (pesquisar na lateral por: Setup Node.js enviroment)
        with:
          node-version: 18

      - name: Cypress run # ---> executar o projeto (pesquisar na lateral por: Cypress.io)
        uses: cypress-io/github-action@v5
        
        continue-on-error: true # ---> caso o apresente erro nÃ£o para o teste
